### ISSUE TITLE
AttributeError: 'SD1ClipModel' object has no attribute 'transformer'

### ISSUE THREAD

**Issue by Nico53425342** [andersxa/comfyui-PromptAttention#5]
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-PromptAttention\clip_attention_mask.py", line 400, in encode
    pre_func = clip.cond_stage_model.transformer.text_model._build_causal_attention_mask
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nicol\Desktop\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'SD1ClipModel' object has no attribute 'transformer'

Prompt executed in 0.01 seconds

no idea how to fix that...

**Comment by MoonMoon82** [comment]
I get the same error message:


```
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "e:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "e:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "e:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\StableDiffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-PromptAttention\clip_attention_mask.py", line 400, in encode
    pre_func = clip.cond_stage_model.transformer.text_model._build_causal_attention_mask
  File "e:\StableDiffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SD1ClipModel' object has no attribute 'transformer'

Prompt executed in 0.07 seconds
```

also does not work for SDXL
